// Copy for the marketplace buy pages. Keep user-facing text here, not in components.
export const MARKET_STRINGS = {
  meta: {
    title: "Buy | UniShare Marketplace",
    description: "Books, laptops, cycles and furniture from students on your campus, at student prices.",
  },
  hero: {
    titleBefore: "Campus,",
    titleAccent: "second-hand.",
    lead: "Books, laptops, cycles and furniture from students who are done with them. Fair prices, picked up on campus.",
    sell: "Sell an item",
    browse: "Browse the market",
  },
  receipt: {
    store: "UNISHARE MARKET",
    title: "Just listed",
    item: "Item",
    price: "Price",
    total: (n) => `${n} ${n === 1 ? "ITEM" : "ITEMS"} ON THE SHELF`,
    thanks: "THANK YOU FOR SHOPPING ON CAMPUS",
    open: (title) => `Open ${title}`,
    loading: "Printing the latest listings",
    empty: "NOTHING LISTED YET",
  },
  categories: {
    label: "Category",
    all: "Everything",
    electronics: "Electronics",
    books: "Books",
    furniture: "Furniture",
    accessories: "Accessories",
    cycles: "Cycles",
    gaming: "Gaming",
    other: "Other",
  },
  conditions: {
    label: "Condition",
    all: "Any condition",
    new: "Brand new",
    "like-new": "Like new",
    good: "Good",
    fair: "Fair",
    damaged: "Needs repair",
  },
  sort: {
    label: "Sort",
    newest: "Newest",
    low: "Price: low to high",
    high: "Price: high to low",
  },
  market: {
    title: "The market",
    count: (n) => (n === 0 ? "Nothing matches" : `${n} ${n === 1 ? "item" : "items"}`),
    searchLabel: "Search the market",
    searchPlaceholder: "Search books, laptops, cycles…",
    clear: "Clear search",
    showMore: "Show more",
    loading: "Loading items",
  },
  card: {
    open: (title) => `View ${title}`,
    free: "Free",
    by: (name) => `by ${name}`,
  },
  when: { today: "Today", yesterday: "Yesterday", days: (n) => `${n} days ago` },
  empty: {
    title: "Nothing matches that",
    body: "Try another word, category or condition.",
    reset: "Clear filters",
    noneTitle: "The market is empty",
    noneBody: "Be the first to list something you no longer need.",
  },
  error: { title: "Couldn't load the market", body: "Check your connection and try again.", retry: "Try again" },
  detail: {
    back: "Marketplace",
    loading: "Loading item",
    notFound: { title: "This item isn't listed any more", body: "It may have been sold or taken down.", cta: "Back to the market" },
    error: { title: "Couldn't load this item", body: "Check your connection and try again.", retry: "Try again" },
    noPhoto: "No photo",
    facts: { condition: "Condition", category: "Category", location: "Pickup at", available: "Available", listed: "Listed" },
    availableNow: "Now",
    about: "About this item",
    noDescription: "The seller didn't add a description.",
    seller: "Seller",
    contact: "Contact",
    contactSignIn: "Sign in to see the seller's contact details",
    share: "Share",
    copied: "Link copied",
    request: {
      title: "Ask to buy",
      lead: "Send the seller a message. They'll get back to you on your email.",
      offer: "Your offer (optional)",
      offerHint: (price) => `Asking ${price}. Leave blank to pay the asking price.`,
      pickup: "Pickup preference (optional)",
      pickups: ["On campus", "At my hostel", "Flexible"],
      message: "Message to the seller",
      messageDefault: "Hi! Is this still available? I'd like to buy it.",
      messageHint: (n) => `Required. ${n}/450`,
      send: "Send request",
      sending: "Sending",
      signIn: "Sign in to buy",
      sent: "Request sent",
      sentBody: "The seller will see it right away. Follow it from your activity.",
      already: "You've already asked about this item.",
      own: "This is your listing.",
      tooShort: "Write a short message",
      badOffer: "Enter a price of zero or more",
      failed: "Couldn't send your request. Please try again.",
      activity: "View my requests",
    },
  },
};
