export const ACTIVITY_STRINGS = {
  hero: {
    lead: "Your",
    accent: "requests.",
    body: "Everything people have asked you for, and everything you've asked others for, across UniShare.",
  },
  summary: {
    waitingTitle: (n) => (n === 1 ? "1 person is waiting for your reply" : `${n} people are waiting for your reply`),
    waitingNone: "Nobody is waiting on you",
    waitingAction: "Reply now",
    sentTitle: (n) => (n === 1 ? "1 of your requests is still pending" : `${n} of your requests are still pending`),
    sentNone: "None of your requests are pending",
    sentAction: "See them",
  },
  tabs: { received: "Received", sent: "Sent" },
  filters: { all: "All", feature: "Feature", status: "Status", statusAll: "Any status", pending: "Waiting", accepted: "Accepted", declined: "Declined", cancelled: "Cancelled" },
  empty: {
    received: { title: "No requests yet", body: "When someone asks for one of your rides, rooms, items or tickets, it shows up here." },
    sent: { title: "You haven't asked for anything yet", body: "Requests you send for rides, rooms, items or tickets show up here." },
    filtered: { title: "Nothing matches", body: "Try another feature or status." },
  },
  failed: (names) => `Couldn't load ${names}. Everything else is up to date.`,
  error: { title: "Couldn't load your requests", body: "Check your connection and try again.", retry: "Try again" },
  signedOut: { title: "Sign in to see your requests", body: "Requests you send and receive across UniShare live here.", cta: "Sign in" },
  done: {
    accept: "Accepted. They'll see it right away.",
    decline: "Declined.",
    cancel: "Request cancelled.",
  },
  yours: { title: "Your posts", body: "Manage what you've posted on each feature." },
  card: {
    from: "From",
    to: "To",
    someone: "Someone",
    listedAt: "Listed at",
    theyOffer: "They offer",
    youOffered: "You offered",
    yourReply: "Your reply:",
    theirReply: "Their reply:",
    call: "Call",
    email: "Email",
    accept: "Accept",
    decline: "Decline",
    withNote: "Reply with a note",
    noteLabel: "Note to send with your answer",
    notePlaceholder: "Add a note, like where to meet or why not (optional)",
    acceptSend: "Accept and send",
    declineSend: "Decline and send",
    back: "Back",
    working: "Saving…",
    ridePassed: "This ride has already left, so the request can't be answered.",
    waitingOnThem: "Waiting for them to reply.",
    cancel: "Cancel request",
    cancelAsk: "Cancel this request?",
    cancelYes: "Yes, cancel",
    keep: "Keep it",
    status: { pending: "Waiting", accepted: "Accepted", declined: "Declined", cancelled: "Cancelled" },
  },
};
