// Copy for the Announcements pages. Keep user-facing text here, not in components.
export const ANNOUNCEMENT_STRINGS = {
  meta: {
    title: "Announcements | UniShare",
    description: "Events, exam updates, club news and campus alerts, in one feed.",
  },
  hero: {
    titleBefore: "Campus,",
    titleAccent: "on air.",
    lead: "Events, exam updates, club news and alerts from around campus. Everything in one feed, newest first.",
    post: "Post an announcement",
  },
  board: {
    title: "Now showing",
    empty: "Nothing on air yet",
    urgent: "Urgent",
    live: "Live",
  },
  tags: {
    label: "Topic",
    all: "Everything",
    general: "General",
    events: "Events",
    academics: "Academics",
    alerts: "Alerts",
    clubs: "Clubs",
  },
  feed: {
    title: "The feed",
    count: (n) => (n === 0 ? "Nothing matches" : `${n} ${n === 1 ? "announcement" : "announcements"}`),
    searchLabel: "Search announcements",
    searchPlaceholder: "Search titles and details",
    clear: "Clear search",
    urgentOnly: "Urgent only",
    showMore: "Show more",
    loading: "Loading announcements",
  },
  day: {
    today: "Today",
    yesterday: "Yesterday",
    now: "now",
    minutes: (n) => `${n} min ago`,
    hours: (n) => `${n} h ago`,
  },
  card: {
    urgent: "Urgent",
    low: "FYI",
    more: "Read more",
    less: "Show less",
    copy: "Copy link",
    copied: "Link copied",
    posted: (time) => `Posted ${time}`,
  },
  empty: {
    title: "Nothing matches that",
    body: "Try another word or topic.",
    reset: "Clear filters",
    noneTitle: "Quiet on campus",
    noneBody: "No announcements yet. Have news to share?",
  },
  error: { title: "Couldn't load announcements", body: "Check your connection and try again.", retry: "Try again" },
  post: {
    meta: { title: "Post an announcement | UniShare", description: "Share an event, update or alert with campus. Every post is reviewed before it goes live." },
    back: "Announcements",
    title: "Post an announcement",
    lead: "Write it once. The preview shows exactly how it will look on the board and in the feed.",
    sections: { headline: "Headline", details: "Details", topics: "Topics", priority: "Priority" },
    fields: {
      title: "Headline",
      titlePlaceholder: "e.g. Library closes early today",
      titleHint: "Short and specific. This is what shows on the board.",
      body: "Details",
      bodyPlaceholder: "What, when, where, and anything people need to bring or do.",
      bodyHint: "Plain text. Line breaks are kept.",
      count: (n, max) => `${n}/${max}`,
      topicsHint: (max) => `Pick up to ${max}. People filter the feed by these.`,
    },
    priority: {
      low: { title: "FYI", body: "Good to know, no rush." },
      normal: { title: "Normal", body: "Most announcements." },
      high: { title: "Urgent", body: "Safety, closures, deadlines today." },
    },
    errors: {
      title: "Add a headline",
      body: "Add some details",
      topics: "Pick at least one topic",
    },
    preview: "Preview",
    previewBoard: "On the board",
    previewFeed: "In the feed",
    placeholderTitle: "Your headline",
    placeholderBody: "Your details will appear here.",
    review: "An admin checks every post before it goes live. This usually takes less than a day.",
    submit: "Send for review",
    submitting: "Sending",
    signIn: { title: "Sign in to post", body: "Announcements are tied to your account so admins can reach you.", cta: "Sign in" },
    failed: "Couldn't send it. Please try again.",
    done: {
      title: "Sent for review",
      body: "We'll put it on air as soon as an admin approves it. You can follow it below.",
      feed: "Back to the feed",
      another: "Post another",
    },
    mine: {
      title: "Your submissions",
      empty: "Nothing yet. Your posts and their status show up here.",
      inReview: "In review",
      live: "Live",
      withdraw: "Withdraw",
      confirmTitle: "Withdraw this post?",
      confirmBody: "It will be deleted and won't go live.",
      confirmOk: "Withdraw",
      keep: "Keep",
      withdrawn: "Post withdrawn",
      withdrawFailed: "Couldn't withdraw it. Please try again.",
    },
  },
  manage: {
    link: "Your announcements",
    meta: { title: "Your announcements | UniShare", description: "Track, edit and withdraw the announcements you posted." },
    back: "Announcements",
    title: "Your announcements",
    lead: "Everything you've posted, with its review status. Edit or withdraw posts that are still in review.",
    post: "Post an announcement",
    filterLabel: "Show",
    filters: { all: "All", review: "In review", live: "Live" },
    stats: { review: (n) => `${n} in review`, live: (n) => `${n} live` },
    edit: "Edit",
    editing: "Editing",
    save: "Save changes",
    saving: "Saving",
    cancel: "Cancel",
    saved: "Changes saved",
    saveFailed: "Couldn't save your changes. Please try again.",
    view: "View in feed",
    withdraw: "Withdraw",
    remove: "Remove",
    confirm: {
      withdrawTitle: "Withdraw this post?",
      withdrawBody: "It will be deleted and won't go live.",
      removeTitle: "Remove this post?",
      removeBody: "It disappears from the feed and the board for everyone.",
      keep: "Keep",
    },
    withdrawn: "Post withdrawn",
    removed: "Post removed",
    deleteFailed: "Couldn't delete it. Please try again.",
    liveNote: "Live posts can't be edited. Remove it and post a corrected version.",
    empty: {
      all: { title: "You haven't posted anything yet", body: "Share an event, an update or an alert with campus." },
      review: { title: "Nothing waiting for review", body: "Posts you send show up here until an admin approves them." },
      live: { title: "Nothing live yet", body: "Approved posts show up here." },
    },
    signIn: { title: "Sign in to see your announcements", body: "Your posts are tied to your account.", cta: "Sign in" },
    error: { title: "Couldn't load your announcements", body: "Check your connection and try again.", retry: "Try again" },
  },
};
