// All user-facing copy for the ride-share landing page.

export const RIDE_STRINGS = {
  meta: {
    title: "Ride Sharing | UniShare",
    description: "Find a ride or share yours with students heading the same way.",
  },
  hero: {
    eyebrow: "UniShare Rides",
    titleFind: "Meet halfway.",
    titleFindAccent: "Ride together.",
    titlePost: "Your empty seats,",
    titlePostAccent: "someone's ride home.",
    leadFind: "Pick where you're starting and where you're headed. We'll show students already on that route.",
    leadPost: "Share your route and seats. Riders going your way can request to join.",
    modeLabel: "What do you want to do?",
    modeFind: "Find a ride",
    modePost: "Post a ride",
    from: "From",
    to: "To",
    fromPlaceholder: "Where are you starting?",
    toPlaceholder: "Where are you going?",
    swap: "Swap start and destination",
    when: "When",
    whenPlaceholder: "Any day",
    date: "Date",
    time: "Time",
    timePlaceholder: "Any time",
    seats: "Seats",
    seatsNeeded: (n) => `${n} ${n === 1 ? "seat" : "seats"} needed`,
    seatsOffered: (n) => `${n} ${n === 1 ? "seat" : "seats"} free`,
    submitFind: "Search rides",
    submitPost: "Continue to details",
    postHint: "Next you'll add price, vehicle and contact details.",
    requiredFrom: "Add a starting point",
    requiredTo: "Add a destination",
    requiredWhen: "Pick a date and time",
    samePlace: "Start and destination can't be the same",
    suggestionsPopular: "Popular on campus",
    suggestionsLive: "On live routes",
    suggestionsMap: "Places on the map",
    suggestionsRoute: (from) => `Often paired with ${from}`,
    ridesOnRoute: (n) => `${n} ${n === 1 ? "ride" : "rides"}`,
    done: "Done",
    clear: "Clear",
    whenPostPlaceholder: "Add a date and time",
    suggestionsLabel: "Suggested places",
    noSuggestions: "No saved places match. Tap Done to use what you typed.",
    seatFewer: "One seat fewer",
    seatMore: "One seat more",
    datePlaceholder: "Pick a date",
    timePickPlaceholder: "Pick a time",
    quickDays: "Quick pick a day",
  },
  stage: {
    label: (from, to) =>
      from && to
        ? `Route preview from ${from} to ${to}`
        : "Route preview: two students' paths meeting at a shared pickup",
    rider: "You",
    driver: "Host",
    meet: "Meet",
    pinLabel: (driver, seats) => `${driver}, ${seats} ${seats === 1 ? "seat" : "seats"} left`,
    seatsShort: (n) => `${n} left`,
    fromFallback: "Start",
    toFallback: "Destination",
    legendStart: "You",
    legendDestination: "Destination",
    mapLabel: (from, to, satellite) => {
      const kind = satellite ? "Satellite map" : "Map";
      return to ? `${kind} of the route from ${from} to ${to}` : `${kind} centred on ${from}`;
    },
    nearby: "Nearby destinations",
    defaultStart: "Starting from campus",
    previewRoute: (from, to) => `Popular route: ${from} to ${to}`,
    travelTime: (minutes) => (minutes >= 60 ? `${Math.floor(minutes / 60)} h ${minutes % 60} min` : `${minutes} min`),
    mapTypeLabel: "Map style",
    mapTypeMap: "Map",
    mapTypeSatellite: "Satellite",
    routeSummary: (km, minutes, mode) =>
      minutes ? `${km} km · about ${minutes} min ${mode === "walk" ? "on foot" : "by road"}` : `About ${km} km away`,
    findingRoute: "Finding the road route",
    checking: (place) => `Finding ${place} on the map`,
    notFound: (place) => `We couldn't find "${place}" in India. Check the spelling, try a landmark, or pick a suggestion.`,
    lookupFailed: "Map search is unavailable right now. You can still search rides.",
    verified: (label, detail) => (detail ? `Found ${label}, ${detail}` : `Found ${label}`),
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    loadingMap: "Loading map",
  },
  live: {
    label: "Live on UniShare",
    ridesToday: "Rides today",
    openSeats: "Open seats",
    avgPrice: "Avg. price per seat",
    activeRoutes: "Active routes",
  },
  manage: {
    eyebrow: "Your rides",
    title: "Manage",
    requestsTitle: "Requests waiting",
    requestsCount: (n) => `${n} waiting`,
    ridesTitle: "My upcoming rides",
    accept: "Accept",
    decline: "Decline",
    accepted: (name) => `Accepted ${name}`,
    declined: (name) => `Declined ${name}`,
    undo: "Undo",
    undone: "Change undone",
    seatsRequested: (n) => `${n} ${n === 1 ? "seat" : "seats"}`,
    pickup: "Pickup",
    requestedAgo: (ago) => `Requested ${ago}`,
    emptyRequestsTitle: "No one is waiting on you",
    emptyRequestsBody: "When a rider asks to join one of your rides, it shows up here.",
    emptyRidesTitle: "No rides on your calendar",
    emptyRidesBody: "Post a route and riders heading the same way can join you.",
    emptyRidesCta: "Post a ride",
    signedOutTitle: "Sign in to manage your rides",
    signedOutBody: "See requests from riders and keep track of the rides you've posted.",
    signIn: "Sign in",
    viewAll: "Manage all rides",
    edit: "Edit",
    cancel: "Cancel ride",
    cancelConfirmTitle: "Cancel this ride?",
    cancelConfirmBody: "Riders with requests will be notified.",
    cancelConfirmOk: "Cancel ride",
    cancelConfirmKeep: "Keep it",
    cancelled: "Ride cancelled",
    seatsFilled: (filled, total) => `${filled} of ${total} seats filled`,
    pendingCount: (n) => `${n} pending`,
    steps: { posted: "Posted", requests: "Requests", full: "Seats filled", ride: "Ride day" },
    editTitle: "Edit ride",
    editSave: "Save changes",
    editCancel: "Close",
    saved: "Ride updated",
    price: "Price per seat",
    tabRequests: "Requests",
    tabRides: "My rides",
    moreRequests: (n) => `${n} more waiting`,
    moreRides: (n) => `${n} more upcoming`,
    acceptLabel: (name) => `Accept ${name}'s request`,
    declineLabel: (name) => `Decline ${name}'s request`,
    stepRequested: "Requested",
    stepDecision: "Your decision",
    statusLabel: "Request status",
    routeFrom: "From",
    routeTo: "to",
    editLabel: (from, to) => `Edit ride from ${from} to ${to}`,
    cancelLabel: (from, to) => `Cancel ride from ${from} to ${to}`,
    editSeatsBooked: (n) => `${n} already booked, so at least ${n}`,
    editSeatsRange: (min, max) => `Between ${min} and ${max}`,
    editTimePast: "Pick a time later than now",
    editPriceRequired: "Add a price of at least 1",
    editFewerSeats: "Fewer seats",
    editMoreSeats: "More seats",
    editCloseLabel: "Close edit ride",
  },
  recent: {
    eyebrow: "Going soon",
    title: "Recent rides",
    filters: { today: "Today", tomorrow: "Tomorrow", week: "This week" },
    filterLabel: "Show rides for",
    request: "Request seat",
    requesting: "Sending",
    requested: "Requested",
    full: "Full",
    yours: "Your ride",
    perSeat: "per seat",
    seatsLeft: (n) => `${n} of`,
    seatsLeftLabel: (left, total) => `${left} of ${total} seats left`,
    seatsLeftShort: (n) => `${n} ${n === 1 ? "seat" : "seats"} left`,
    emptyTitle: (filter) => `No rides ${filter === "today" ? "left today" : filter === "tomorrow" ? "tomorrow yet" : "this week yet"}`,
    emptyBody: "Post your route and be the first ride on it.",
    emptyCta: "Post a ride",
    errorTitle: "Couldn't load rides",
    errorBody: "Check your connection and try again.",
    retry: "Try again",
    viewAll: "See all rides",
    requestSent: (driver) => `Request sent to ${driver}`,
    requestFailed: "Couldn't send your request",
    signInToRequest: "Sign in to request a seat",
    carouselLabel: "Recent rides",
    vehicle: "Vehicle",
    driverFallback: "UniShare student",
    position: (current, total) => `${current} / ${total}`,
    cardHeading: (from, to, day, time) => `From ${from} to ${to}, departs ${day} at ${time}`,
    optionLabel: (label, n) => `${label}, ${n} ${n === 1 ? "ride" : "rides"}`,
  },
  find: {
    meta: {
      title: "Find a ride | UniShare",
      description: "Search upcoming student rides by route, day and seats, and request a seat.",
    },
    title: "Rides on your line",
    titleFor: (from, to) =>
      from && to ? `${from} to ${to}` : to ? `Rides to ${to}` : from ? `Rides from ${from}` : "Rides on your line",
    lead: "Every upcoming student ride, matched to your route. Pick one and request a seat.",
    back: "Ride share",
    tripTitle: "Your trip",
    tripSummaryEmpty: "Where are you going?",
    tripSummaryAnyDay: "Any day",
    tripEdit: "Edit trip",
    showResults: (n) => (n === 1 ? "Show 1 ride" : `Show ${n} rides`),
    summary: {
      label: "Search summary",
      rides: (n) => (n === 1 ? "1 ride" : `${n} rides`),
      from: (price) => `from ${price}`,
      next: (when) => `next ${when}`,
      inMinutes: (n) => (n < 60 ? `in ${n} min` : n < 1440 ? `in ${Math.round(n / 60)} h` : `in ${Math.round(n / 1440)} d`),
    },
    ribbon: {
      label: "Pick a day",
      any: "Any day",
      count: (n) => (n === 0 ? "None" : n === 1 ? "1 ride" : `${n} rides`),
      optionLabel: (day, n) => `${day}, ${n === 1 ? "1 ride" : `${n} rides`}`,
    },
    filters: {
      title: "Refine",
      sortLabel: "Sort rides",
      sort: { best: "Best match", soonest: "Soonest", cheapest: "Cheapest", seats: "Most seats" },
      windowLabel: "Departure time",
      windows: { morning: "Morning", afternoon: "Afternoon", evening: "Evening", night: "Night" },
      windowHint: { morning: "5 am to 12 pm", afternoon: "12 to 5 pm", evening: "5 to 9 pm", night: "9 pm to 5 am" },
      priceLabel: "Max price per seat",
      priceAny: "Any price",
      priceUpTo: (price) => `Up to ${price}`,
      reset: "Reset filters",
      open: "Filters",
      active: (n) => (n === 1 ? "1 filter on" : `${n} filters on`),
    },
    view: { label: "Show results as", list: "List", map: "Map" },
    groups: {
      exact: "On your route",
      close: "Close matches",
      closeHint: "These share one end of your trip.",
      all: "Upcoming rides",
    },
    match: { exact: "Exact route", close: "One end matches" },
    card: {
      details: "Details",
      request: "Request seat",
      requestAgain: "Request again",
      pending: "Request sent",
      confirmed: "Seat confirmed",
      declined: "Declined",
      cancelled: "Cancelled",
      full: "Full",
      yours: "Your ride",
      perSeat: "per seat",
      free: "Free",
      heading: (from, to, day, time) => `${from} to ${to}, ${day} at ${time}`,
    },
    details: {
      title: "Ride details",
      close: "Close details",
      driver: "Offered by",
      vehicle: "Vehicle",
      vehicleUnknown: "Not specified",
      price: "Per seat",
      seats: "Seats left",
      departs: "Departs",
      notes: "Notes from the host",
      contact: "Contact the host",
      contactHint: "Shared because your seat is confirmed.",
      seatsToRequest: "Seats",
      message: "Message to the host",
      messageHint: "Say where you'll wait, or anything the host should know.",
      messageDefault: (from, to) => `Hi! I'd like to join your ride from ${from} to ${to}.`,
      send: (n) => (n === 1 ? "Request 1 seat" : `Request ${n} seats`),
      sending: "Sending request",
      signIn: "Sign in to request a seat",
      sentTitle: "Request sent",
      sentBody: (driver) => `${driver} has been notified. Their answer will show here and in your activity.`,
      viewRequests: "View my requests",
      done: "Done",
      statusPending: "You've requested this ride. Waiting for the host to reply.",
      statusConfirmed: "You're in. Your seat is confirmed.",
      statusDeclined: "The host couldn't take this request. You can ask again.",
      statusCancelled: "This request was cancelled. You can ask again.",
      own: "This is your ride. Manage it from the ride-share page.",
      full: "This ride is full.",
    },
    empty: {
      title: "No rides on this route yet",
      titleDay: "No rides that day",
      titleFiltered: "No rides match these filters",
      body: "Post your trip and riders heading the same way can join you.",
      bodyDay: "Try another day, or post your own ride.",
      bodyFiltered: "Loosen a filter to see more rides.",
      anyDay: "Show every day",
      post: "Post this ride",
      reset: "Reset filters",
    },
    error: { title: "Couldn't load rides", body: "Check your connection and try again.", retry: "Try again" },
    resultsLabel: "Search results",
    resultsLive: (n) => (n === 0 ? "No rides found" : n === 1 ? "1 ride found" : `${n} rides found`),
    mapEmpty: "Pick a ride to see its route",
    postRide: "Post a ride",
  },
  post: {
    meta: {
      title: "Post a ride | UniShare",
      description: "Share your route, seats and fare so students heading the same way can ride with you.",
    },
    back: "Ride share",
    title: "Post your ride",
    lead: "Three quick steps. Riders on your route can request a seat as soon as it's live.",
    steps: { route: "Route and time", ride: "Car and fare", contact: "Contact and notes" },
    stepLabel: "Steps",
    stepOf: (n, total) => `Step ${n} of ${total}`,
    next: "Continue",
    backStep: "Back",
    publish: "Publish ride",
    publishing: "Publishing",
    vehicle: "Your vehicle",
    vehiclePlaceholder: "For example, Swift Dzire, white",
    vehicleHint: "Model and colour help riders spot you at pickup.",
    fare: "Fare per seat",
    fareHint: "Riders see this price for each seat.",
    fareLower: "Lower the fare by 10",
    fareRaise: "Raise the fare by 10",
    fareTypical: (price) => `Rides on this route usually charge ${price}`,
    fareMatch: (price) => `Use ${price}`,
    fareEarn: (total, seats) => `Up to ${total} if all ${seats} ${seats === 1 ? "seat fills" : "seats fill"}`,
    contact: "How riders reach you",
    contactHint: "Only riders you accept see these. Add at least one.",
    contactTypes: { mobile: "Mobile", email: "Email", instagram: "Instagram" },
    contactPlaceholders: { mobile: "10-digit mobile number", email: "you@university.edu", instagram: "@handle" },
    notes: "Notes for riders",
    notesOptional: "Optional",
    notesPlaceholder: "Pickup point, luggage space, stops on the way",
    preview: "How riders will see it",
    previewDay: "Pick a day",
    previewFare: "₹ —",
    draftRestored: "We restored your unfinished ride.",
    draftDiscard: "Start over",
    errors: {
      vehicle: "Add your vehicle",
      fare: "Set a fare above zero",
      contact: "Add at least one way to reach you",
      mobile: "Enter a 10-digit mobile number",
      email: "Enter a valid email address",
      instagram: "Enter an Instagram handle",
      past: "Pick a time in the future",
      fixStep: "Fix the highlighted fields to continue.",
      failed: "Couldn't publish your ride. Please try again.",
    },
    signIn: {
      title: "Sign in to post a ride",
      body: "Rides are tied to your student account, so riders know who they're travelling with.",
      cta: "Sign in",
    },
    done: {
      title: "Your ride is live",
      body: (to) => `Riders heading to ${to} can find it now. You'll see requests on the ride-share page.`,
      view: "See it in search",
      another: "Post another ride",
      manage: "Manage my rides",
    },
  },
  my: {
    meta: {
      title: "Manage rides | UniShare",
      description: "Rides you're offering and rides you've asked to join, in one place.",
    },
    back: "Ride share",
    title: "Your rides",
    lead: "Answer requests, keep your rides up to date and track the seats you've asked for.",
    post: "Post a ride",
    find: "Find a ride",
    stats: {
      label: "At a glance",
      hosting: (n) => (n === 1 ? "1 ride coming up" : `${n} rides coming up`),
      waiting: (n) => (n === 1 ? "1 request waiting" : `${n} requests waiting`),
      joining: (n) => (n === 1 ? "1 seat booked" : `${n} seats booked`),
    },
    tabsLabel: "Show",
    tabs: { hosting: "Offering", joining: "Joining" },
    filters: { upcoming: "Upcoming", past: "Past", cancelled: "Cancelled" },
    filtersLabel: "Filter rides",
    host: {
      pending: (n) => (n === 1 ? "1 request" : `${n} requests`),
      riders: "Riders",
      ridersCount: (n, total) => `${n} of ${total} seats taken`,
      noRiders: "No riders yet. Requests show up here as they come in.",
      requestsTitle: "Waiting for your answer",
      riderSeats: (n) => (n === 1 ? "1 seat" : `${n} seats`),
      menu: "Ride actions",
      edit: "Edit ride",
      cancel: "Cancel ride",
      view: "View in search",
      expand: "Show riders and requests",
      collapse: "Hide riders and requests",
      statusPast: "Completed",
      statusCancelled: "Cancelled",
      confirmCancelTitle: "Cancel this ride?",
      confirmCancelBody: (n) =>
        n > 0
          ? `${n === 1 ? "1 rider has" : `${n} riders have`} a seat or request on it. They'll see it's cancelled.`
          : "It will disappear from search right away.",
      confirmCancelOk: "Cancel ride",
      confirmKeep: "Keep it",
      cancelled: "Ride cancelled",
      cancelFailed: "Couldn't cancel the ride. Please try again.",
    },
    joining: {
      status: { pending: "Waiting", confirmed: "Confirmed", declined: "Declined", cancelled: "Cancelled" },
      statusHint: {
        pending: "The host hasn't answered yet.",
        confirmed: "Your seat is booked. Contact details are in the ride.",
        declined: "The host couldn't take this request.",
        cancelled: "You cancelled this request.",
      },
      hostedBy: (name) => `Offered by ${name}`,
      seats: (n) => (n === 1 ? "1 seat" : `${n} seats`),
      cancel: "Cancel request",
      view: "Open ride",
      again: "Find another ride",
      confirmCancelTitle: "Cancel your request?",
      confirmCancelBody: "The host won't see it any more. You can request again later.",
      confirmCancelOk: "Cancel request",
      cancelled: "Request cancelled",
      cancelFailed: "Couldn't cancel the request.",
    },
    empty: {
      hostingUpcoming: { title: "No rides coming up", body: "Post a route and students heading the same way can join you." },
      hostingPast: { title: "No past rides yet", body: "Rides you've offered show up here after they leave." },
      hostingCancelled: { title: "Nothing cancelled", body: "Rides you cancel are kept here for reference." },
      joiningUpcoming: { title: "You haven't asked to join a ride", body: "Find a ride on your route and request a seat." },
      joiningPast: { title: "No past trips yet", body: "Rides you joined show up here after they leave." },
      joiningCancelled: { title: "Nothing cancelled", body: "Requests that were declined or cancelled show up here." },
    },
    error: { title: "Couldn't load your rides", body: "Check your connection and try again.", retry: "Try again" },
    signIn: {
      title: "Sign in to manage your rides",
      body: "See requests for the rides you offer and the seats you've asked for.",
      cta: "Sign in",
    },
  },
  fab: {
    post: "Post a ride",
  },
  errors: {
    generic: "Something went wrong. Please try again.",
    respondFailed: "Couldn't update that request. It's back in your queue.",
    cancelFailed: "Couldn't cancel the ride. Please try again.",
    updateFailed: "Couldn't save your changes.",
  },
};
