// All user-facing copy for the ride-share landing page.

export const RIDE_STRINGS = {
  meta: {
    title: "Ride Sharing | UniShare",
    description: "Find a ride or share yours with students heading the same way.",
  },
  hero: {
    eyebrow: "UniShare Rides",
    titleFind: "Meet halfway.",
    titleFindAccent: "Ride together.",
    titlePost: "Your empty seats,",
    titlePostAccent: "someone's ride home.",
    leadFind: "Pick where you're starting and where you're headed. We'll show students already on that route.",
    leadPost: "Share your route and seats. Riders going your way can request to join.",
    modeLabel: "What do you want to do?",
    modeFind: "Find a ride",
    modePost: "Post a ride",
    from: "From",
    to: "To",
    fromPlaceholder: "Where are you starting?",
    toPlaceholder: "Where are you going?",
    swap: "Swap start and destination",
    when: "When",
    whenPlaceholder: "Any day",
    date: "Date",
    time: "Time",
    timePlaceholder: "Any time",
    seats: "Seats",
    seatsNeeded: (n) => `${n} ${n === 1 ? "seat" : "seats"} needed`,
    seatsOffered: (n) => `${n} ${n === 1 ? "seat" : "seats"} free`,
    submitFind: "Search rides",
    submitPost: "Continue to details",
    postHint: "Next you'll add price, vehicle and contact details.",
    requiredFrom: "Add a starting point",
    requiredTo: "Add a destination",
    requiredWhen: "Pick a date and time",
    samePlace: "Start and destination can't be the same",
    suggestionsPopular: "Popular on campus",
    suggestionsLive: "On live routes",
    suggestionsMap: "Places on the map",
    suggestionsRoute: (from) => `Often paired with ${from}`,
    ridesOnRoute: (n) => `${n} ${n === 1 ? "ride" : "rides"}`,
    done: "Done",
    clear: "Clear",
    whenPostPlaceholder: "Add a date and time",
    suggestionsLabel: "Suggested places",
    noSuggestions: "No saved places match. Tap Done to use what you typed.",
    seatFewer: "One seat fewer",
    seatMore: "One seat more",
    datePlaceholder: "Pick a date",
    timePickPlaceholder: "Pick a time",
    quickDays: "Quick pick a day",
  },
  stage: {
    label: (from, to) =>
      from && to
        ? `Route preview from ${from} to ${to}`
        : "Route preview: rider and driver paths meeting at a shared pickup",
    rider: "You",
    driver: "Driver",
    meet: "Meet",
    pinLabel: (driver, seats) => `${driver}, ${seats} ${seats === 1 ? "seat" : "seats"} left`,
    seatsShort: (n) => `${n} left`,
    fromFallback: "Start",
    toFallback: "Destination",
    legendStart: "You",
    legendDestination: "Destination",
    mapLabel: (from, to, satellite) => {
      const kind = satellite ? "Satellite map" : "Map";
      return to ? `${kind} of the route from ${from} to ${to}` : `${kind} centred on ${from}`;
    },
    nearby: "Nearby destinations",
    defaultStart: "Starting from campus",
    previewRoute: (from, to) => `Popular route: ${from} to ${to}`,
    travelTime: (minutes) => (minutes >= 60 ? `${Math.floor(minutes / 60)} h ${minutes % 60} min` : `${minutes} min`),
    mapTypeLabel: "Map style",
    mapTypeMap: "Map",
    mapTypeSatellite: "Satellite",
    routeSummary: (km, minutes, mode) =>
      minutes ? `${km} km · about ${minutes} min ${mode === "walk" ? "on foot" : "by road"}` : `About ${km} km away`,
    findingRoute: "Finding the road route",
    checking: (place) => `Finding ${place} on the map`,
    notFound: (place) => `We couldn't find "${place}" near campus. Try a landmark or pick a suggestion.`,
    lookupFailed: "Map search is unavailable right now. You can still search rides.",
    verified: (label, detail) => (detail ? `Found ${label}, ${detail}` : `Found ${label}`),
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    loadingMap: "Loading map",
  },
  live: {
    label: "Live on UniShare",
    ridesToday: "Rides today",
    openSeats: "Open seats",
    avgPrice: "Avg. price per seat",
    activeRoutes: "Active routes",
  },
  manage: {
    eyebrow: "Your rides",
    title: "Manage",
    requestsTitle: "Requests waiting",
    requestsCount: (n) => `${n} waiting`,
    ridesTitle: "My upcoming rides",
    accept: "Accept",
    decline: "Decline",
    accepted: (name) => `Accepted ${name}`,
    declined: (name) => `Declined ${name}`,
    undo: "Undo",
    undone: "Change undone",
    seatsRequested: (n) => `${n} ${n === 1 ? "seat" : "seats"}`,
    pickup: "Pickup",
    requestedAgo: (ago) => `Requested ${ago}`,
    emptyRequestsTitle: "No one is waiting on you",
    emptyRequestsBody: "When a rider asks to join one of your rides, it shows up here.",
    emptyRidesTitle: "No rides on your calendar",
    emptyRidesBody: "Post a route and riders heading the same way can join you.",
    emptyRidesCta: "Post a ride",
    signedOutTitle: "Sign in to manage your rides",
    signedOutBody: "See requests from riders and keep track of the rides you've posted.",
    signIn: "Sign in",
    viewAll: "View all activity",
    edit: "Edit",
    cancel: "Cancel ride",
    cancelConfirmTitle: "Cancel this ride?",
    cancelConfirmBody: "Riders with requests will be notified.",
    cancelConfirmOk: "Cancel ride",
    cancelConfirmKeep: "Keep it",
    cancelled: "Ride cancelled",
    seatsFilled: (filled, total) => `${filled} of ${total} seats filled`,
    pendingCount: (n) => `${n} pending`,
    steps: { posted: "Posted", requests: "Requests", full: "Seats filled", ride: "Ride day" },
    editTitle: "Edit ride",
    editSave: "Save changes",
    editCancel: "Close",
    saved: "Ride updated",
    price: "Price per seat",
    tabRequests: "Requests",
    tabRides: "My rides",
    moreRequests: (n) => `${n} more waiting`,
    moreRides: (n) => `${n} more upcoming`,
    acceptLabel: (name) => `Accept ${name}'s request`,
    declineLabel: (name) => `Decline ${name}'s request`,
    stepRequested: "Requested",
    stepDecision: "Your decision",
    statusLabel: "Request status",
    routeFrom: "From",
    routeTo: "to",
    editLabel: (from, to) => `Edit ride from ${from} to ${to}`,
    cancelLabel: (from, to) => `Cancel ride from ${from} to ${to}`,
    editSeatsBooked: (n) => `${n} already booked, so at least ${n}`,
    editSeatsRange: (min, max) => `Between ${min} and ${max}`,
    editTimePast: "Pick a time later than now",
    editPriceRequired: "Add a price of at least 1",
    editFewerSeats: "Fewer seats",
    editMoreSeats: "More seats",
    editCloseLabel: "Close edit ride",
  },
  recent: {
    eyebrow: "Going soon",
    title: "Recent rides",
    filters: { today: "Today", tomorrow: "Tomorrow", week: "This week" },
    filterLabel: "Show rides for",
    request: "Request seat",
    requesting: "Sending",
    requested: "Requested",
    full: "Full",
    yours: "Your ride",
    perSeat: "per seat",
    seatsLeft: (n) => `${n} of`,
    seatsLeftLabel: (left, total) => `${left} of ${total} seats left`,
    seatsLeftShort: (n) => `${n} ${n === 1 ? "seat" : "seats"} left`,
    emptyTitle: (filter) => `No rides ${filter === "today" ? "left today" : filter === "tomorrow" ? "tomorrow yet" : "this week yet"}`,
    emptyBody: "Post your route and be the first ride on it.",
    emptyCta: "Post a ride",
    errorTitle: "Couldn't load rides",
    errorBody: "Check your connection and try again.",
    retry: "Try again",
    viewAll: "See all rides",
    requestSent: (driver) => `Request sent to ${driver}`,
    requestFailed: "Couldn't send your request",
    signInToRequest: "Sign in to request a seat",
    carouselLabel: "Recent rides",
    vehicle: "Vehicle",
    driverFallback: "Student driver",
    position: (current, total) => `${current} / ${total}`,
    cardHeading: (from, to, day, time) => `From ${from} to ${to}, departs ${day} at ${time}`,
    optionLabel: (label, n) => `${label}, ${n} ${n === 1 ? "ride" : "rides"}`,
  },
  fab: {
    post: "Post a ride",
  },
  errors: {
    generic: "Something went wrong. Please try again.",
    respondFailed: "Couldn't update that request. It's back in your queue.",
    cancelFailed: "Couldn't cancel the ride. Please try again.",
    updateFailed: "Couldn't save your changes.",
  },
};
