// Copy for the Resources pages. Keep user-facing text here, not in components.
export const RESOURCE_STRINGS = {
  meta: {
    title: "Resources | UniShare",
    description: "Notes, past papers, tools and campus links that students recommend.",
  },
  hero: {
    titleBefore: "Campus,",
    titleAccent: "bookmarked.",
    lead: "Notes, past papers, tools and campus links, picked by students and checked by admins.",
    suggest: "Suggest a resource",
    manage: "Your suggestions",
  },
  shelf: {
    title: "New on the shelf",
    open: (title) => `Find ${title} in the library`,
    empty: "The shelf is empty for now",
  },
  categories: {
    label: "Category",
    all: "Everything",
    academics: "Academics",
    tools: "Tools",
    campus: "Campus",
    docs: "Docs",
    media: "Media",
  },
  types: {
    label: "Type",
    all: "Any type",
    link: "Link",
    pdf: "PDF",
    doc: "Doc",
    video: "Video",
  },
  library: {
    title: "The library",
    count: (n) => (n === 0 ? "Nothing matches" : `${n} ${n === 1 ? "resource" : "resources"}`),
    searchLabel: "Search resources",
    searchPlaceholder: "Search titles, notes and tags",
    clear: "Clear search",
    showMore: "Show more",
    loading: "Loading resources",
  },
  card: {
    open: "Open",
    openLabel: (title) => `Open ${title} in a new tab`,
    copy: "Copy link",
    copied: "Copied",
    added: (when) => `Added ${when}`,
  },
  empty: {
    title: "Nothing matches that",
    body: "Try another word, category or type.",
    reset: "Clear filters",
    noneTitle: "The library is empty",
    noneBody: "Know a great set of notes or a handy tool? Suggest it.",
  },
  error: { title: "Couldn't load resources", body: "Check your connection and try again.", retry: "Try again" },
  when: { today: "today", yesterday: "yesterday", days: (n) => `${n} days ago` },
  suggest: {
    meta: { title: "Suggest a resource | UniShare", description: "Share notes, papers, tools or campus links. Admins check every suggestion." },
    back: "Resources",
    title: "Suggest a resource",
    lead: "Paste a link and add a few details. The preview shows exactly how it will look in the library.",
    sections: { link: "The link", about: "About it", shelf: "Where it goes" },
    fields: {
      url: "Link",
      urlPlaceholder: "https://",
      urlHint: "Google Drive, a website, a YouTube video, a PDF…",
      detected: (domain) => `From ${domain}`,
      title: "Title",
      titlePlaceholder: "e.g. DSA notes, unit 1–5",
      desc: "Short note (optional)",
      descPlaceholder: "What it covers and who it helps.",
      count: (n, max) => `${n}/${max}`,
      category: "Category",
      type: "Type",
      typeAuto: "We guessed this from the link. Change it if it's wrong.",
      tags: "Tags (optional)",
      tagsPlaceholder: "Type a tag and press Enter",
      tagsHint: (max) => `Up to ${max}. Course codes and topics work well.`,
      removeTag: (tag) => `Remove tag ${tag}`,
    },
    errors: {
      url: "Paste a full link that starts with http:// or https://",
      title: "Add a title",
      category: "Pick a category",
    },
    preview: "Preview",
    review: "An admin checks every suggestion before it goes on the shelf.",
    submit: "Send for review",
    submitting: "Sending",
    signIn: { title: "Sign in to suggest", body: "Suggestions are tied to your account so admins can reach you.", cta: "Sign in" },
    failed: "Couldn't send it. Please try again.",
    done: { title: "Sent for review", body: "It goes on the shelf as soon as an admin approves it.", library: "Back to the library", another: "Suggest another" },
  },
  manage: {
    meta: { title: "Your suggestions | UniShare", description: "Track, edit and withdraw the resources you suggested." },
    back: "Resources",
    title: "Your suggestions",
    lead: "Everything you've suggested, with its review status. Edit or withdraw suggestions that are still in review.",
    suggest: "Suggest a resource",
    filterLabel: "Show",
    filters: { all: "All", review: "In review", live: "Live" },
    stats: { review: (n) => `${n} in review`, live: (n) => `${n} live` },
    inReview: "In review",
    live: "Live",
    edit: "Edit",
    editing: "Editing",
    save: "Save changes",
    saving: "Saving",
    cancel: "Cancel",
    saved: "Changes saved",
    saveFailed: "Couldn't save your changes. Please try again.",
    view: "View in library",
    withdraw: "Withdraw",
    remove: "Remove",
    confirm: {
      withdrawTitle: "Withdraw this suggestion?",
      withdrawBody: "It will be deleted and won't go on the shelf.",
      removeTitle: "Remove this resource?",
      removeBody: "It disappears from the library for everyone.",
      keep: "Keep",
    },
    withdrawn: "Suggestion withdrawn",
    removed: "Resource removed",
    deleteFailed: "Couldn't delete it. Please try again.",
    liveNote: "Live resources can't be edited. Remove it and suggest a corrected version.",
    empty: {
      all: { title: "You haven't suggested anything yet", body: "Share notes, papers or a handy tool with campus." },
      review: { title: "Nothing waiting for review", body: "Suggestions show up here until an admin approves them." },
      live: { title: "Nothing live yet", body: "Approved suggestions show up here." },
    },
    signIn: { title: "Sign in to see your suggestions", body: "Your suggestions are tied to your account.", cta: "Sign in" },
    error: { title: "Couldn't load your suggestions", body: "Check your connection and try again.", retry: "Try again" },
  },
};
