// Copy for the profile pages. Keep user-facing text here, not in components.
export const PROFILE_STRINGS = {
  meta: {
    title: "Your profile | UniShare",
    description: "Your UniShare campus pass, everything you share on campus, and your settings.",
  },
  hero: {
    greeting: (name) => `Hey, ${name}.`,
    fallbackName: "there",
    lead: "This is your campus pass. It's what people see when you share a ride, a room or anything else.",
    noBio: "Add a line about yourself so people know who they're meeting.",
    edit: "Edit profile",
    share: "Share my pass",
    copied: "Link copied",
    needsHandle: "Pick a username to get a shareable pass.",
  },
  completeness: {
    title: (pct) => (pct === 100 ? "Your pass is complete" : `Your pass is ${pct}% complete`),
    items: { photo: "Photo", name: "Name", handle: "Username", campus: "Campus", bio: "About you", phone: "Phone" },
    done: ": done",
    todo: ": missing",
  },
  card: {
    pass: "CAMPUS PASS",
    member: (when) => `Member since ${when}`,
    flip: "Flip pass",
    flipBack: "Flip back",
    scan: "Scan to open my pass",
    noHandle: "Pick a username to get a QR code",
    label: (name) => `Campus pass for ${name}`,
  },
  footprint: {
    title: "Your campus footprint",
    lead: "Everything you've put out there. Tap a row to manage it.",
    loading: "Counting your posts",
    count: (n) => (n === 1 ? "1 post" : `${n} posts`),
    totalLabel: (n) => (n === 1 ? "post across campus" : "posts across campus"),
    none: "Nothing yet",
    stamps: {
      rides: "Rides",
      rooms: "Rooms",
      market: "Marketplace",
      tickets: "Tickets",
      lostfound: "Lost & Found",
      announcements: "Announcements",
      resources: "Resources",
    },
    open: (label, n) => `${label}: ${n === 1 ? "1 post" : `${n} posts`}. Manage`,
  },
  activity: {
    title: "Recent activity",
    empty: "Your posts will show up here.",
    emptyCta: "Find something to share",
    ride: (from, to) => `${from} → ${to}`,
    when: { today: "Today", yesterday: "Yesterday", days: (n) => `${n} days ago` },
  },
  settings: {
    title: "Settings",
    appearance: "Appearance",
    appearanceHint: "Pick a look, or follow your device.",
    modes: { light: "Light", dark: "Dark", system: "System" },
    account: "Account & security",
    email: "Email",
    signInWith: "Sign-in method",
    methods: { google: "Google", password: "Email and password", both: "Google, and email and password" },
    memberSince: "Member since",
    lastLogin: "Last signed in",
    password: "Password",
    passwordSet: "Set a password so you can also sign in with your email.",
    changePassword: "Change password",
    setPassword: "Set a password",
    activity: "Requests and activity",
    signOut: "Sign out",
    signOutAll: "Sign out of this device",
    danger: "Danger zone",
    deleteTitle: "Delete account",
    deleteBody: "Permanently removes your account, your profile and everything you've posted. This can't be undone.",
    delete: "Delete account",
    loading: "Loading account details",
  },
  passwordDialog: {
    titleChange: "Change password",
    titleSet: "Set a password",
    current: "Current password",
    next: "New password",
    confirm: "Confirm new password",
    show: "Show passwords",
    rules: { length: "At least 8 characters", mix: "Letters and numbers", match: "Both new passwords match" },
    strength: ["Too short", "Weak", "Okay", "Strong", "Very strong"],
    save: "Save password",
    saving: "Saving",
    cancel: "Cancel",
    changed: "Password changed",
    set: "Password set. You can now sign in with your email too.",
    failed: "Couldn't update your password. Please try again.",
  },
  deleteDialog: {
    title: "Delete your account?",
    lead: "This removes, for good:",
    items: ["Your profile and campus pass", "Every ride, room, item, ticket and lost & found post", "Your announcements, resources and requests"],
    typeLabel: (word) => `Type ${word} to confirm`,
    word: "DELETE",
    password: "Your password",
    keep: "Keep my account",
    confirm: "Delete forever",
    deleting: "Deleting",
    failed: "Couldn't delete your account. Please try again.",
    done: "Your account has been deleted.",
  },
  edit: {
    title: "Edit profile",
    lead: "Your pass updates as you type.",
    photo: "Photo",
    changePhoto: "Change photo",
    removePhoto: "Use initials instead",
    photoHint: "JPEG, PNG, WebP or GIF, up to 5 MB.",
    name: "Display name",
    handle: "Username",
    handleHint: "Letters, numbers and underscores. 3–20 characters.",
    checking: "Checking…",
    available: "Available",
    taken: "Already taken",
    campus: "Campus",
    campusPlaceholder: "e.g. Lovely Professional University",
    phone: "Phone (optional)",
    phoneHint: "Only shown to people you deal with.",
    bio: "About you",
    bioPlaceholder: "Third-year CSE, cycles everywhere, always up for a road trip.",
    count: (n, max) => `${n}/${max}`,
    save: "Save changes",
    saving: "Saving",
    cancel: "Cancel",
    close: "Close",
    saved: "Profile saved",
    failed: "Couldn't save your profile. Please try again.",
  },
  signIn: { title: "Sign in to see your profile", body: "Your pass, your posts and your settings live here.", cta: "Sign in" },
  error: { title: "Couldn't load your profile", body: "Check your connection and try again.", retry: "Try again" },
  public: {
    meta: { title: "Campus pass | UniShare", description: "A student's UniShare campus pass." },
    notFound: { title: "No pass with that username", body: "Check the link, or the student may have changed their username.", cta: "Go to UniShare" },
    about: "About",
    own: "This is your pass. Edit it from your profile.",
    toProfile: "Open my profile",
  },
};
