// Settings page copy.

export const SETTINGS_STRINGS = {
  meta: { title: "Settings · UniShare", description: "Your account, sign-in, appearance and data on UniShare." },
  title: "Settings",
  lead: "Your account, how you sign in, and how UniShare looks.",
  nav: { account: "Account", signin: "Sign-in & security", appearance: "Appearance", privacy: "Privacy & data", danger: "Delete account" },
  signedOut: { title: "Sign in to manage your account", body: "You can still change how UniShare looks below.", cta: "Sign in" },
  account: {
    title: "Account",
    noName: "Your name",
    noHandle: "No username yet",
    edit: "Edit profile",
    pass: "View public pass",
    pickHandle: "Pick a username",
    email: "Email",
    memberSince: "Member since",
    lastLogin: "Last signed in",
    loadFailed: "Couldn't load your account details.",
    retry: "Try again",
  },
  signin: {
    title: "Sign-in & security",
    methods: "Ways to sign in",
    methodsHint: "You can use any of these to get into your account.",
    google: "Google",
    password: "Email and password",
    on: "On",
    off: "Not set up",
    passwordRow: "Password",
    passwordHint: { has: "Change it any time. You'll need your current password.", none: "Add one so you can also sign in with your email." },
    change: "Change",
    set: "Set password",
    device: "This device",
    deviceHint: "Sign out here. You'll stay signed in on other devices until their session ends (7 days).",
    signOut: "Sign out",
  },
  appearance: {
    title: "Appearance",
    hint: "Pick a look, or follow your device.",
    modes: { light: "Light", dark: "Dark", system: "System" },
  },
  privacy: {
    title: "Privacy & data",
    visible: "What others can see",
    visibleHint: "Posts and their contact details are public. Your profile shows your name, photo and bio.",
    visibleCta: "Read more",
    copy: "Get a copy of your data",
    copyHint: "Email us from your account's address and we'll send you what we hold.",
    copyCta: "Email us",
    device: "Saved on this device",
    deviceHint: "Your room shortlist, unfinished ride post and cached notices. Clearing them doesn't touch your account.",
    deviceCta: "Clear",
    cleared: "Cleared data saved on this device",
    nothing: "Nothing saved on this device",
  },
  danger: {
    title: "Delete account",
    body: "Permanently removes your account, your profile and everything you've posted. This can't be undone.",
    cta: "Delete account",
  },
};
