// All user-facing copy for the housing landing page.

export const HOUSING_STRINGS = {
  meta: {
    title: "Housing | UniShare",
    description: "Rooms near campus listed by students, with real rents, beds and move-in dates.",
  },
  manageLink: "Manage listings",
  hero: {
    eyebrow: "UniShare Housing",
    title: "Swipe to your",
    titleAccent: "next room.",
    lead: "Tell us what you need in one line, then save the rooms you like and compare them side by side.",
    list: "List your room",
    browse: "See all rooms",
  },
  sentence: {
    label: "Describe the room you need",
    parts: { start: "I need", room: "room", near: "near", under: "under", from: "from" },
    bedsAny: "any size",
    beds: (n) => (n === "4+" ? "a 4+ bed" : `a ${n} bed`),
    typeBeds: "Type number of beds",
    typeBudget: "Type a monthly rent",
    typeDate: "Or pick a date",
    apply: "Apply",
    areaAny: "anywhere",
    budgetAny: "any rent",
    moveInAny: "any time",
    moveInNow: "now",
    pick: { beds: "Room size", area: "Area", budget: "Monthly rent up to", moveIn: "Move in" },
    areaSearch: "Type an area",
    areaSuggestions: "Areas with rooms",
    areaUse: (text) => `Use "${text}"`,
    change: (part, value) => `${part}: ${value}. Change`,
    match: (n) => (n === 0 ? "No rooms match" : n === 1 ? "1 room matches" : `${n} rooms match`),
    reset: "Start over",
    done: "Done",
  },
  deck: {
    label: "Rooms to swipe through",
    hint: "Drag right to save, left to skip",
    save: "Save room",
    skip: "Skip room",
    undo: "Undo last swipe",
    saved: (title) => `Saved ${title}`,
    skipped: (title) => `Skipped ${title}`,
    position: (i, n) => `Room ${i} of ${n}`,
    open: "Open room",
    doneTitle: "You've seen every match",
    doneBody: "Compare what you saved, or change your search to see more rooms.",
    again: "Go through again",
    emptyTitle: "Nothing to swipe yet",
    emptyBody: "Change a word in your search to see more rooms.",
    saveBadge: "SAVE",
    skipBadge: "SKIP",
  },
  shortlist: {
    title: "Your shortlist",
    count: (n) => (n === 1 ? "1 saved" : `${n} saved`),
    empty: "Rooms you save show up here.",
    compare: "Compare",
    compareTitle: "Compare saved rooms",
    remove: (title) => `Remove ${title} from shortlist`,
    clear: "Clear shortlist",
    close: "Close",
    rows: { rent: "Rent", beds: "Beds", moveIn: "Move in", area: "Location" },
    view: "View room",
    cheapest: "Lowest rent",
    soonest: "Soonest",
  },
  results: {
    title: "Every room that fits",
    sortLabel: "Sort rooms",
    sort: { newest: "Newest", cheapest: "Lowest rent", soonest: "Soonest move-in" },
    perMonth: "/month",
    beds: (n) => (n === 1 ? "1 bed" : `${n} beds`),
    availableNow: "Available now",
    availableFrom: (date) => `From ${date}`,
    photos: (n) => (n === 1 ? "1 photo" : `${n} photos`),
    noPhoto: "No photos yet",
    new: "New",
    showMore: "Show more rooms",
    seeAll: "See all rooms",
    loadingLabel: "Loading rooms",
    live: (n) => (n === 0 ? "No rooms match" : n === 1 ? "1 room matches" : `${n} rooms match`),
    save: (title) => `Save ${title}`,
    unsave: (title) => `Remove ${title} from shortlist`,
  },
  areas: {
    eyebrow: "Neighbourhoods",
    title: "Where students are renting",
    rooms: (n) => (n === 1 ? "1 room" : `${n} rooms`),
    median: (rent) => `Typical ${rent}`,
    pick: (name) => `Show rooms in ${name}`,
    selected: "Showing",
  },
  empty: {
    title: "No rooms match yet",
    body: "Change a word in your search. New rooms are posted every week.",
    reset: "Start over",
    noneTitle: "No rooms listed yet",
    noneBody: "Be the first to list a room near campus.",
  },
  error: { title: "Couldn't load rooms", body: "Check your connection and try again.", retry: "Try again" },
  list: {
    eyebrow: "Have a spare room?",
    title: "List it in a couple of minutes.",
    body: "Add photos, rent and a move-in date. Students looking near campus see it straight away.",
    steps: ["Snap a few photos", "Set rent and beds", "Pick a move-in date"],
    cta: "List your room",
  },
  safety: {
    title: "Renting safely",
    tips: [
      { title: "Visit before you pay", body: "See the room in person, or ask for a live video call, before sending any money." },
      { title: "Meet in daylight", body: "Go with a friend for the first viewing and tell someone where you'll be." },
      { title: "Get it in writing", body: "Agree rent, deposit and notice period in a message or a simple agreement." },
    ],
  },
  post: {
    meta: { title: "List your room | UniShare", description: "Add photos, rent and a move-in date. Students near campus see your room right away." },
    back: "Housing",
    title: "List your room",
    lead: "Fill it in once. The card on the right is exactly what students will see.",
    sections: { photos: "Photos", basics: "The basics", about: "About the room", contact: "How students reach you" },
    photos: {
      drop: "Drop photos here or browse",
      hint: (max, mb) => `Up to ${max} photos, ${mb} MB each. The first one is the cover.`,
      browse: "Browse photos",
      add: "Add more",
      cover: "Cover",
      makeCover: "Make cover",
      remove: "Remove photo",
      tooBig: (name, mb) => `${name} is over ${mb} MB`,
      notImage: (name) => `${name} isn't an image`,
      tooMany: (max) => `You can add up to ${max} photos`,
      count: (n, max) => `${n} of ${max}`,
    },
    fields: {
      title: "Listing title",
      titlePlaceholder: "Sunny single near Law Gate",
      location: "Location",
      locationPlaceholder: "Area, landmark or street",
      locationHint: "Start with the area name, for example Law Gate, Phagwara.",
      rent: "Monthly rent",
      beds: "Beds",
      bedsFewer: "One bed fewer",
      bedsMore: "One bed more",
      moveIn: "Available from",
      moveInNow: "Today",
      moveInNextMonth: "1st of next month",
      description: "Description",
      descriptionPlaceholder: "What's included, house rules, who it suits, how far to campus",
      optional: "Optional",
      mobile: "Mobile",
      email: "Email",
      instagram: "Instagram",
      contactHint: "Add at least one. Only shown on your listing page.",
    },
    errors: {
      title: "Give your listing a title",
      location: "Add where the room is",
      rent: "Set a monthly rent above zero",
      beds: "Add at least one bed",
      moveIn: "Pick a date from today on",
      contact: "Add at least one way to reach you",
      email: "Enter a valid email address",
      mobile: "Enter a valid mobile number",
      fix: "Fix the highlighted fields to publish.",
      failed: "Couldn't publish your room. Please try again.",
    },
    checklist: { title: "Ready to publish", photos: "Photos", basics: "Title and place", price: "Rent and beds", date: "Move-in date", contact: "Contact" },
    previewLabel: "Preview",
    previewTitle: "Your room title",
    previewPlace: "Location",
    publish: "Publish listing",
    publishing: "Publishing",
    signIn: { title: "Sign in to list a room", body: "Listings are tied to your student account so people know who they're contacting.", cta: "Sign in" },
    done: { title: "Your room is live", body: "Students looking near campus can find it now.", view: "View listing", another: "List another room", browse: "Back to housing" },
  },
  search: {
    meta: { title: "Search rooms | UniShare", description: "Every room listed near campus, filtered by area, rent, beds and move-in date." },
    back: "Housing",
    title: "Find a room",
    count: (n, more) => (n === 0 ? "No rooms match" : `${n}${more ? "+" : ""} ${n === 1 ? "room" : "rooms"} match`),
    list: "List your room",
    view: { label: "Show rooms as", grid: "Grid", list: "List" },
    ruler: { label: "Rent of each matching room", hint: "Each dot is a room. Hover or tap one to find it.", jump: (title, rent) => `${title}, ${rent} a month` },
    loadMore: "Load more rooms",
    loading: "Loading rooms",
    end: "That's every room for this search.",
  },
  tag: {
    readyNow: "Ready now",
    inDays: (n) => (n === 1 ? "Free tomorrow" : `Free in ${n} days`),
    from: (d) => `Free from ${d}`,
    beds: (n) => (n === 1 ? "1 bed" : `${n} beds`),
  },
  detail: {
    back: "All rooms",
    loading: "Loading room",
    notFound: { title: "This room isn't listed any more", body: "It may have been taken or removed. There are more rooms near campus.", cta: "Browse rooms" },
    error: { title: "Couldn't load this room", body: "Check your connection and try again.", retry: "Try again" },
    photo: (i, n) => `Photo ${i} of ${n}`,
    prev: "Previous photo",
    next: "Next photo",
    noPhotos: "No photos yet",
    perMonth: "/month",
    facts: { beds: "Beds", moveIn: "Available", listed: "Listed" },
    about: "About this room",
    noDescription: "The owner hasn't added a description yet.",
    contact: "Contact",
    contactSignIn: "Sign in to see contact details",
    save: "Save room",
    saved: "Saved",
    share: "Share",
    copied: "Link copied",
    request: {
      title: "Ask to rent",
      lead: "Send a request with your dates. The owner replies from their requests page.",
      moveIn: "Move in on",
      occupants: "People",
      fewer: "One person fewer",
      more: "One person more",
      stay: "How long",
      stays: ["One semester", "6 months", "1 year"],
      message: "Message to the owner",
      messageHint: (n) => `At least 10 characters. ${n}/900`,
      messageDefault: "Hi! I'm a student looking for a room near campus and I'd like to know more about this one.",
      send: "Send request",
      sending: "Sending",
      signIn: "Sign in to send a request",
      sent: "Request sent",
      sentBody: "The owner will see it right away. You can follow it from your activity.",
      already: "You've already asked about this room.",
      own: "This is your listing.",
      tooShort: "Write at least 10 characters",
      pastDate: "Pick a date from today on",
      failed: "Couldn't send your request. Please try again.",
      activity: "View my requests",
      manage: "See requests on your rooms",
    },
  },
  manage: {
    meta: { title: "Manage rooms | UniShare", description: "Your room listings, the requests on them, and the rooms you asked about." },
    back: "Housing",
    title: "Your rooms",
    lead: "Approve or decline people asking about your listings, and follow the rooms you asked about.",
    post: "List a room",
    find: "Find a room",
    tabsLabel: "What to show",
    tabs: { listings: "My listings", sent: "My requests" },
    stats: { label: "Summary", waiting: (n) => `${n} waiting for you`, listings: (n) => `${n} listing${n === 1 ? "" : "s"}`, approved: (n) => `${n} approved` },
    status: { pending: "Waiting", approved: "Approved", rejected: "Declined", cancelled: "Cancelled" },
    listing: {
      view: "View",
      remove: "Remove listing",
      noRequests: "No requests yet. Share the link to get more eyes on it.",
      requests: (n) => `${n} request${n === 1 ? "" : "s"}`,
      moveIn: (d) => `Move in ${d}`,
      people: (n) => `${n} ${n === 1 ? "person" : "people"}`,
      approve: "Approve",
      decline: "Decline",
      reply: "Reply (optional)",
      replyHint: "Sent with your answer, e.g. when to visit.",
      yourReply: "Your reply",
      approved: (name) => `Approved ${name}`,
      declined: (name) => `Declined ${name}`,
      respondFailed: "Couldn't save your answer. Please try again.",
      confirmTitle: "Remove this listing?",
      confirmBody: (n) => (n ? `${n} pending request${n === 1 ? "" : "s"} will close with it.` : "It disappears from search right away."),
      confirmOk: "Remove",
      keep: "Keep",
      removed: "Listing removed",
      removeFailed: "Couldn't remove the listing. Please try again.",
    },
    sent: {
      owner: (name) => `Listed by ${name}`,
      reply: "Owner's reply",
      cancel: "Cancel request",
      confirmTitle: "Cancel this request?",
      confirmBody: "The owner won't see it any more. You can ask again later.",
      confirmOk: "Cancel request",
      keep: "Keep",
      cancelled: "Request cancelled",
      cancelFailed: "Couldn't cancel the request. Please try again.",
    },
    empty: {
      listings: { title: "No listings yet", body: "Post a room and requests from students show up here." },
      sent: { title: "You haven't asked about any rooms", body: "Find a room you like and send a request from its page." },
    },
    signIn: { title: "Sign in to manage your rooms", body: "Your listings and requests are tied to your account.", cta: "Sign in" },
    error: { title: "Couldn't load your rooms", body: "Check your connection and try again.", retry: "Try again" },
  },
};
