// Copy for the Lost & Found pages. Keep user-facing text here, not in components.
export const LOST_FOUND_STRINGS = {
  meta: {
    title: "Lost & Found | UniShare",
    description: "Lost something on campus or picked something up? Post it, search the board, and get it back to its owner.",
  },
  hero: {
    titleLead: "Lost it?",
    title: "Someone",
    titleAccent: "found it.",
    lead: "Search what students have handed in, or post what you lost or found. Most things go home within a few days.",
    modeLabel: "What happened",
    modes: { lost: "I lost something", found: "I found something" },
    report: { lost: "Report a lost item", found: "Report a found item" },
    browse: "See the whole board",
    searchLabel: { lost: "What did you lose?", found: "What did you find?" },
    searchPlaceholder: "Wallet, ID card, keys…",
    clear: "Clear search",
  },
  categories: {
    label: "Kind of item",
    all: "Anything",
    wallet: "Wallets",
    id: "ID cards",
    keys: "Keys",
    charger: "Chargers",
    watch: "Watches",
    phone: "Phones",
    audio: "Earphones",
    laptop: "Laptops",
    bag: "Bags",
    bottle: "Bottles",
    glasses: "Glasses",
    jewel: "Jewellery",
    books: "Books",
    other: "Other",
  },
  lens: {
    tag: "Found",
    found: (n) => `${n} found, waiting to go home`,
    looking: (n) => `${n} still being looked for`,
    // Only seen under the glass while the visitor steers it.
    notes: {
      backpack: "Side pocket. Always.",
      audio: "Always the left one.",
      calculator: "Exam hall, row B.",
      bottle: "Canteen, second shelf.",
      glasses: "Checked your head?",
      laptop: "Library desk, again.",
      book: "Overdue since March.",
      umbrella: "Was it ever yours?",
      charger: "Still by your bed.",
    },
    ink: "You found the secret spot.",
  },
  board: {
    title: "On the board",
    lead: "Everything that's still waiting for its owner.",
    filterLabel: "Show",
    filters: { all: "All", lost: "Lost", found: "Found" },
    count: (n) => (n === 0 ? "Nothing matches" : `${n} ${n === 1 ? "item" : "items"}`),
    showMore: "Show more",
    loading: "Loading the board",
  },
  card: {
    lost: "Missing",
    found: "Found",
    lastSeen: "Last seen",
    foundAt: "Found at",
    ticket: (code) => `Claim #${code}`,
    noPlace: "Place not given",
    open: (name) => `Open details for ${name}`,
  },
  when: {
    today: "Today",
    yesterday: "Yesterday",
    days: (n) => `${n} days ago`,
    unknown: "Date not given",
  },
  view: {
    close: "Close",
    photo: (i, n) => `Photo ${i} of ${n}`,
    where: { lost: "Last seen at", found: "Found at" },
    when: { lost: "Lost on", found: "Found on" },
    anonymous: "a student",
    posted: (name, when) => `Posted by ${name} · ${when}`,
    about: "Details",
    noDescription: "No extra details were added.",
    contact: "Get in touch",
    contactSignIn: "Sign in to see contact details",
    proof: "Ask for a detail only the owner would know before handing anything over.",
  },
  empty: {
    title: "Nothing matches that",
    body: "Try another word or kind of item, or post it so others can look out for it.",
    reset: "Clear filters",
    noneTitle: "The board is empty",
    noneBody: "Be the first to post something lost or found on campus.",
  },
  error: { title: "Couldn't load the board", body: "Check your connection and try again.", retry: "Try again" },
  tips: {
    title: "Handing it back safely",
    items: [
      { title: "Ask a proof question", body: "Colour, sticker, lock screen, what's inside. The owner knows; a stranger guesses." },
      { title: "Meet somewhere public", body: "Library desk, canteen or the security office. Daytime is best." },
      { title: "Mark it resolved", body: "Once it's home, close the post so people stop looking." },
    ],
  },
  report: {
    meta: { title: "Report an item | UniShare", description: "Post something you lost or found on campus. Students see it on the Lost & Found board right away." },
    back: "Lost & Found",
    title: "Report an item",
    lead: "Fill it in once. The preview card is exactly what goes on the board.",
    modeLabel: "What happened",
    modes: {
      lost: { title: "I lost something", body: "Goes up as a Missing poster." },
      found: { title: "I found something", body: "Goes up as a claim ticket." },
    },
    sections: { what: "What is it", where: "Where and when", photos: "Photos", contact: "How people reach you" },
    fields: {
      name: "Item name",
      namePlaceholder: { lost: "e.g. Black leather wallet", found: "e.g. Blue water bottle" },
      looksLike: (kind) => `Filed under ${kind}`,
      description: "Details",
      descriptionHint: {
        lost: "Colour, brand, stickers, what was inside. The more specific, the faster it comes back.",
        found: "Describe it, but keep one detail back. Ask the owner for it before you hand it over.",
      },
      place: { lost: "Where did you last see it?", found: "Where did you find it?" },
      placeHint: "Building, room or landmark",
      recentPlaces: "Places on the board",
      date: { lost: "Date lost", found: "Date found" },
      today: "Today",
      yesterday: "Yesterday",
      time: "Time (optional)",
      mobile: "Mobile number",
      email: "Email",
      instagram: "Instagram",
      contactHint: "Add at least one. It's shown only to signed-in students.",
    },
    errors: {
      name: "Name the item",
      description: "Add a few details",
      place: "Say where",
      date: "Pick a date that isn't in the future",
      contact: "Add at least one way to reach you",
      mobile: "Enter a 10-digit mobile number",
      email: "Enter a valid email",
      instagram: "Letters, numbers, dots and underscores only",
    },
    preview: "Preview",
    checklist: { label: "Ready to post", what: "What it is", where: "Where and when", photos: "A photo (optional)", contact: "A way to reach you", done: ": done", todo: ": not yet" },
    publish: { lost: "Post Missing poster", found: "Post claim ticket" },
    publishing: "Posting",
    signIn: "Sign in to post",
    failed: "Couldn't post it. Please try again.",
    done: {
      title: { lost: "Your poster is up", found: "Your ticket is up" },
      body: { lost: "Students can see it now. We'll show it to anyone searching for something like it.", found: "Thanks for handing it in. The owner can claim it from the board." },
      board: "See it on the board",
      another: "Report another item",
    },
  },
  claim: {
    title: { found: "This is mine", lost: "I found it" },
    lead: { found: "Tell the finder how you know it's yours.", lost: "Let the owner know where it is now." },
    message: { found: "Message to the finder", lost: "Message to the owner" },
    messageHint: (n) => `At least 10 characters. ${n}/1000`,
    proof: "Proof only the owner would know (optional)",
    proofHint: "Lock screen, sticker, what's inside…",
    send: "Send",
    sending: "Sending",
    sent: "Sent. They'll get back to you.",
    already: "You've already sent a request for this.",
    own: "This is your post.",
    signIn: "Sign in to respond",
    tooShort: "Write at least 10 characters",
    failed: "Couldn't send it. Please try again.",
  },
};
