import { theme as antdTheme } from "antd";

/** Ant Design ConfigProvider theme generated from the ride tokens. */
export default function buildAntdTheme(t) {
  const c = t.color;
  const dark = t.mode === "dark";
  return {
    algorithm: dark ? antdTheme.darkAlgorithm : antdTheme.defaultAlgorithm,
    hashed: true,
    token: {
      colorPrimary: c.action,
      colorInfo: c.action,
      colorLink: c.accentText,
      colorSuccess: c.success,
      colorError: c.danger,
      colorWarning: c.warning,
      colorText: c.text,
      colorTextSecondary: c.textSecondary,
      colorTextTertiary: c.textMuted,
      colorTextQuaternary: c.textMuted,
      colorTextPlaceholder: c.textMuted,
      colorBgContainer: c.surface,
      colorBgElevated: c.surface,
      colorBgLayout: "transparent",
      colorBgMask: c.scrim,
      colorBorder: c.borderStrong,
      colorBorderSecondary: c.border,
      colorFillSecondary: c.surfaceInteractive,
      colorFillTertiary: c.surfaceInteractive,
      colorFillQuaternary: c.surfaceAlt,
      controlItemBgActive: c.actionSoft,
      controlItemBgActiveHover: c.actionSoftStrong,
      controlItemBgHover: c.surfaceInteractive,
      controlOutline: c.actionSoftStrong,
      fontFamily: t.typography.family,
      fontSize: 14,
      borderRadius: t.radius.sm,
      borderRadiusLG: t.radius.md,
      borderRadiusSM: t.radius.xs,
      controlHeight: t.layout.touch,
      controlHeightLG: t.layout.controlHeightLg,
      controlHeightSM: 32,
      boxShadow: t.elevation[2],
      boxShadowSecondary: t.elevation[3],
      motionDurationMid: `${t.motion.duration.base}s`,
      motionDurationSlow: `${t.motion.duration.slow}s`,
      motionEaseOut: "cubic-bezier(0.22, 1, 0.36, 1)",
      wireframe: false,
    },
    components: {
      Select: {
        optionSelectedBg: c.actionSoft,
        optionSelectedColor: c.text,
        optionActiveBg: c.surfaceInteractive,
        optionPadding: "10px 12px",
        optionHeight: 44,
      },
      DatePicker: {
        cellActiveWithRangeBg: c.actionSoft,
        cellHoverBg: c.surfaceInteractive,
        activeBorderColor: c.action,
        hoverBorderColor: c.borderStrong,
        cellHeight: 32,
        cellWidth: 40,
        timeColumnWidth: 64,
        timeCellHeight: 36,
      },
      Segmented: {
        trackBg: c.surfaceInteractive,
        itemSelectedBg: c.surface,
        itemSelectedColor: c.text,
        itemColor: c.textOnInset,
        itemHoverColor: c.text,
        itemHoverBg: "transparent",
        trackPadding: 4,
        borderRadius: t.radius.pill,
        borderRadiusSM: t.radius.pill,
      },
      Tabs: {
        itemColor: c.textMuted,
        itemSelectedColor: c.text,
        itemHoverColor: c.text,
        inkBarColor: c.action,
        titleFontSize: 15,
        horizontalItemPadding: "12px 4px",
        horizontalItemGutter: 24,
      },
      Tag: {
        defaultBg: c.surfaceInteractive,
        defaultColor: c.textOnInset,
        borderRadiusSM: t.radius.pill,
      },
      Timeline: {
        dotBg: c.surface,
        tailColor: c.border,
        tailWidth: 2,
        itemPaddingBottom: 10,
      },
      Steps: {
        dotSize: 10,
        dotCurrentSize: 12,
        titleLineHeight: 18,
        descriptionMaxWidth: 160,
      },
      Avatar: {
        containerSize: 36,
        containerSizeSM: 28,
        containerSizeLG: 44,
        groupOverlapping: -10,
        groupBorderColor: c.surface,
        fontSize: 14,
      },
      Statistic: {
        contentFontSize: 30,
        titleFontSize: 13,
      },
      Skeleton: {
        gradientFromColor: c.surfaceInteractive,
        gradientToColor: dark ? "rgba(255, 255, 255, 0.10)" : "rgba(18, 35, 58, 0.04)",
        borderRadiusSM: t.radius.xs,
      },
      Empty: {
        colorTextDescription: c.textMuted,
      },
      Popconfirm: {
        zIndexPopup: 1400,
      },
      Notification: {
        zIndexPopup: 1500,
        width: 360,
      },
      InputNumber: {
        activeBorderColor: c.action,
        hoverBorderColor: c.borderStrong,
        handleVisible: true,
      },
    },
  };
}
